import React from 'react';
import { Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useAppContext } from '../context/AppContext';
import { COLORS } from '../theme';

export default function CalendarScreen() {
  const { calendarTasks, notionConnected, setNotionConnected } = useAppContext();
  const grouped = calendarTasks.reduce((acc, task) => { const key = task.dueDate || '마감일 미정'; acc[key] = [...(acc[key] || []), task]; return acc; }, {});
  return (
    <SafeAreaView style={styles.safeArea} edges={['top']}>
      <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
        <View style={styles.header}><Text style={styles.headerTitle}>캘린더</Text><View style={styles.headerBadge}><Text style={styles.headerBadgeText}>{calendarTasks.length}개</Text></View></View>
        <View style={styles.notionCard}><View style={styles.notionTop}><View style={styles.notionIconWrap}><Ionicons name="calendar-clear-outline" size={22} color={COLORS.primary} /></View><View style={{ flex: 1 }}><Text style={styles.notionTitle}>{notionConnected ? '외부 캘린더 연결됨' : '외부 캘린더 연결 대기'}</Text><Text style={styles.notionDesc}>캘린더 할일을 외부 캘린더로 내보낼 수 있습니다.</Text></View></View><TouchableOpacity style={[styles.notionBtn, notionConnected && styles.notionBtnConnected]} onPress={() => { if (!notionConnected) { setNotionConnected(true); return; } Alert.alert('내보내기 완료', '캘린더로 할일을 내보냈습니다.'); }} activeOpacity={0.85}><Ionicons name={notionConnected ? 'cloud-upload-outline' : 'link-outline'} size={18} color="#FFFFFF" /><Text style={styles.notionBtnText}>{notionConnected ? '캘린더로 내보내기' : '캘린더 연결하기'}</Text></TouchableOpacity></View>
        <Text style={styles.sectionTitle}>등록된 할일</Text>
        {calendarTasks.length === 0 ? <View style={styles.emptyCard}><Ionicons name="calendar-outline" size={54} color={COLORS.border} /><Text style={styles.emptyTitle}>등록된 할일이 없어요</Text><Text style={styles.emptyDesc}>회의 상세에서 제안된 할일을 검토하거나 직접 할일을 등록해보세요.</Text></View> : Object.entries(grouped).map(([date, tasks]) => <View key={date} style={styles.dayCard}><View style={styles.dayHeader}><Text style={styles.dayTitle}>{date}</Text><Text style={styles.dayCount}>{tasks.length}개</Text></View>{tasks.map((task) => <View key={task.id} style={styles.taskItem}><View style={styles.taskDot} /><View style={{ flex: 1 }}><Text style={styles.taskTitle}>{task.title}</Text><Text style={styles.taskMeta}>{task.assignee || '담당자 미정'} · {task.source}</Text></View><View style={styles.taskStatusBadge}><Text style={styles.taskStatusText}>{task.status}</Text></View></View>)}</View>)}
      </ScrollView>
    </SafeAreaView>
  );
}
const styles = StyleSheet.create({ safeArea: { flex: 1, backgroundColor: COLORS.background }, scrollContent: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 40 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }, headerTitle: { fontSize: 24, fontWeight: '700', color: COLORS.text, letterSpacing: 0 }, headerBadge: { backgroundColor: '#EEF2FF', borderRadius: 10, paddingHorizontal: 10, paddingVertical: 5 }, headerBadgeText: { color: COLORS.primary, fontWeight: '700', fontSize: 12 }, notionCard: { backgroundColor: COLORS.surface, borderRadius: 18, padding: 18, marginBottom: 24, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 6, elevation: 3 }, notionTop: { flexDirection: 'row', alignItems: 'center', gap: 12 }, notionIconWrap: { width: 46, height: 46, borderRadius: 13, backgroundColor: '#EEF2FF', alignItems: 'center', justifyContent: 'center' }, notionTitle: { fontSize: 16, fontWeight: '700', color: COLORS.text }, notionDesc: { fontSize: 12, color: COLORS.subtext, lineHeight: 18, marginTop: 3 }, notionBtn: { marginTop: 16, height: 48, borderRadius: 14, backgroundColor: COLORS.primary, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 }, notionBtnConnected: { backgroundColor: COLORS.secondary }, notionBtnText: { color: '#FFFFFF', fontWeight: '700', fontSize: 15 }, sectionTitle: { fontSize: 17, fontWeight: '700', color: COLORS.text, marginBottom: 12 }, emptyCard: { backgroundColor: COLORS.surface, borderRadius: 16, padding: 32, alignItems: 'center' }, emptyTitle: { fontSize: 16, fontWeight: '700', color: COLORS.subtext, marginTop: 14 }, emptyDesc: { fontSize: 12, color: '#A0AEC0', lineHeight: 18, textAlign: 'center', marginTop: 6 }, dayCard: { backgroundColor: COLORS.surface, borderRadius: 16, padding: 16, marginBottom: 12, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 4, elevation: 2 }, dayHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }, dayTitle: { fontSize: 15, fontWeight: '700', color: COLORS.primary }, dayCount: { fontSize: 12, color: COLORS.subtext, fontWeight: '600' }, taskItem: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, paddingVertical: 10, borderTopWidth: 1, borderTopColor: '#F1F5F9' }, taskDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: COLORS.success, marginTop: 5 }, taskTitle: { fontSize: 13, fontWeight: '700', color: COLORS.text }, taskMeta: { fontSize: 11, color: COLORS.subtext, marginTop: 3 }, taskStatusBadge: { backgroundColor: '#D1FAE5', borderRadius: 6, paddingHorizontal: 7, paddingVertical: 2 }, taskStatusText: { color: COLORS.success, fontSize: 11, fontWeight: '700' } });
