const rawVariant = (typeof process !== 'undefined' && process.env?.EXPO_PUBLIC_UI_VARIANT) || 'toss';

const variantPresets = {
  toss: {
    label: 'Toss Clean',
    reference: 'Toss, Linear',
    primary: '#2563EB',
    primaryDark: '#1D4ED8',
    secondary: '#06B6D4',
    background: '#F6F8FC',
    surface: '#FFFFFF',
    panel: '#F8FAFC',
    text: '#121826',
    subtext: '#667085',
    border: '#E5EAF2',
    inputBg: '#F2F5FA',
    chip: '#EAF1FF',
    chipText: '#1D4ED8',
    navigation: '#FFFFFF',
    tabInactive: '#98A2B3',
    success: '#12B981',
    warning: '#F59E0B',
    error: '#EF4444',
    shadowOpacity: 0.07,
    shadowRadius: 14,
    elevation: 4,
    radius: { xs: 8, sm: 10, md: 14, lg: 18, xl: 24, pill: 999 },
  },
  notion: {
    label: 'Notion Paper',
    reference: 'Notion, Apple Notes',
    primary: '#2F3437',
    primaryDark: '#111827',
    secondary: '#B45309',
    background: '#F7F6F2',
    surface: '#FFFEFC',
    panel: '#F1F0EB',
    text: '#1F2328',
    subtext: '#6B6F76',
    border: '#E1DFD8',
    inputBg: '#F1F0EB',
    chip: '#EEECE5',
    chipText: '#2F3437',
    navigation: '#FFFEFC',
    tabInactive: '#9B9A95',
    success: '#2F9E69',
    warning: '#C88719',
    error: '#D14343',
    shadowOpacity: 0.035,
    shadowRadius: 8,
    elevation: 1,
    radius: { xs: 6, sm: 8, md: 10, lg: 12, xl: 16, pill: 999 },
  },
  calendar: {
    label: 'Calendar Material',
    reference: 'Google Calendar, Gmail',
    primary: '#1A73E8',
    primaryDark: '#1557B0',
    secondary: '#34A853',
    background: '#F8FBFF',
    surface: '#FFFFFF',
    panel: '#F1F7FE',
    text: '#202124',
    subtext: '#5F6368',
    border: '#DADCE0',
    inputBg: '#F1F3F4',
    chip: '#E8F0FE',
    chipText: '#1967D2',
    navigation: '#FFFFFF',
    tabInactive: '#80868B',
    success: '#188038',
    warning: '#F9AB00',
    error: '#D93025',
    shadowOpacity: 0.09,
    shadowRadius: 10,
    elevation: 3,
    radius: { xs: 8, sm: 10, md: 12, lg: 16, xl: 22, pill: 999 },
  },
  slack: {
    label: 'Workspace Bold',
    reference: 'Slack, Discord',
    primary: '#4A154B',
    primaryDark: '#350D36',
    secondary: '#1264A3',
    background: '#F7F3F8',
    surface: '#FFFFFF',
    panel: '#F0E7F2',
    text: '#1D1C1D',
    subtext: '#616061',
    border: '#E6DDE8',
    inputBg: '#F4EEF6',
    chip: '#EFE3F1',
    chipText: '#4A154B',
    navigation: '#FFFFFF',
    tabInactive: '#8F7A91',
    success: '#2EB67D',
    warning: '#ECB22E',
    error: '#E01E5A',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
    radius: { xs: 7, sm: 9, md: 12, lg: 16, xl: 20, pill: 999 },
  },
};

const selectedVariant = variantPresets[rawVariant] ? rawVariant : 'toss';
const active = variantPresets[selectedVariant];

export const UI_VARIANT = selectedVariant;
export const DESIGN_VARIANTS = Object.entries(variantPresets).map(([id, preset]) => ({
  id,
  label: preset.label,
  reference: preset.reference,
}));

export const RADIUS = active.radius;

export const COLORS = {
  primary: active.primary,
  primaryDark: active.primaryDark,
  secondary: active.secondary,
  background: active.background,
  surface: active.surface,
  panel: active.panel,
  text: active.text,
  textStrong: active.primaryDark,
  subtext: active.subtext,
  border: active.border,
  success: active.success,
  warning: active.warning,
  error: active.error,
  inputBg: active.inputBg,
  chip: active.chip,
  chipText: active.chipText,
  navigation: active.navigation,
  tabInactive: active.tabInactive,
  placeholder: '#98A2B3',
  onPrimary: '#FFFFFF',
  successSoft: '#ECFDF5',
  warningSoft: '#FFFBEB',
  errorSoft: '#FEF2F2',
};

export const CARD_SHADOW = {
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: active.shadowOpacity,
  shadowRadius: active.shadowRadius,
  elevation: active.elevation,
};

export const colors = {
  bg: COLORS.background,
  surface: COLORS.surface,
  panel: COLORS.panel,
  text: COLORS.text,
  muted: COLORS.subtext,
  line: COLORS.border,
  primary: COLORS.primary,
  primaryDark: COLORS.primaryDark,
  mint: COLORS.success,
  amber: COLORS.warning,
  red: COLORS.error,
  ink: COLORS.textStrong,
  chip: COLORS.chip,
  chipText: COLORS.chipText,
};

export const shadow = CARD_SHADOW;
